variable "vpc_cidr_block" {}
variable "region" {}
variable "az_count" {}
variable "instance_type" {}
variable "number_of_instances" {}
variable "ami_id" {}
variable "ambiente" {}
variable "billing" {}
variable "dono" {}
variable "projeto" {}
variable "ec2_name" {}
variable "key_name" {}
variable "vpc_id" {}
variable "sub_net_id" {}
variable "sg_name" {}
variable "t_sg_name" {}