---
- name: Install Nginx
   package:
      name: nginx
      state: present
  - name: Service Nginx Enable
    service:
      name: nginx
      enabled: yes
      state: started
    notify:
    - Reboot nginx